version: '3'

services:


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: konyhatunder
      MYSQL_PASSWORD: konyhatunder
      MYSQL_DATABASE: konyhatunder
      MYSQL_ROOT_PASSWORD: konyhatunder
  backend:
    restart: always
    build: ./backend
    container_name: backend
    hostname: konyhatunder-backend
    depends_on:
      - db
    ports:
      - 8081:8081