version: '3'
services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: percona:ps-8
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: konyhatunder
      MYSQL_PASSWORD: konyhatunder
      MYSQL_DATABASE: konyhatunder
      MYSQL_ROOT_PASSWORD: password
  backend:
    restart: always
    build: ./backend
    container_name: backend
    hostname: konyhatunder-backend
    ports:
      - 8081:8081

