server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:db}:${DB_PORT:3306}/konyhatunder
    username: ${DB_USER:konyhatunder}
    password: ${DB_PASSWORD:konyhatunder}
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create