server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://db:3306/konyhatunder
    username: konyhatunder
    password: konyhatunder
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create